<?php
/**
 * This file is part of the PositibeLabs Projects.
 *
 * (c) Pedro Carlos Abreu <pcabreus@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Positibe\Sylius\FeePlugin\Form\DataTransformer;

use Symfony\Component\Form\Extension\Core\DataTransformer\MoneyToLocalizedStringTransformer;


/**
 * Class MoneyPercentViewTransformer
 * @package Positibe\Sylius\FeePlugin\Form\Transformer
 *
 * @author Pedro Carlos Abreu <pcabreus@gmail.com>
 */
class MoneyPercentViewTransformer extends MoneyToLocalizedStringTransformer
{
    protected $object;

    public function __construct(
        $scale = 2,
        $grouping = true,
        $roundingMode = self::ROUND_HALF_UP,
        $divisor = 1,
        $object = null
    ) {
        parent::__construct($scale, $grouping, $roundingMode, $divisor);
        $this->object = $object;
    }

    public function transform($value)
    {
        if ($this->object && $this->object->isPercent()) {
            return $value;
        }

        return parent::transform($value); // TODO: Change the autogenerated stub
    }


    public function reverseTransform($value)
    {
        $value = parent::reverseTransform($value);

        return null === $value ? null : (int)round($value);
    }

}